baseurl = "https://cssandstuff.github.io/kuaka"
defaultContentLanguage = "en"
disableKinds = ["RSS"]
enableRobotsTXT = true
languageCode = "en-us"
theme = "kuaka"
title = "Kuaka"
[languages.en]
languageName = "English"
weight = 0
[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = -99
[languages.jp]
languageName = "Japanese"
weight = 10
[[languages.jp.menu.main]]
name = "ホーム"
url = "/jp"
weight = -99
