baseurl = "https://kuakatranslations.co.nz/"
defaultContentLanguage = "en"
disableKinds = ["RSS"]
enableRobotsTXT = true
googleAnalytics = "UA-7167547-13"
languageCode = "en-us"
theme = "kuaka"
title = "Kuaka Translations"
[languages.en]
languageName = "English"
weight = 0
[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = -99
[languages.jp]
languageName = "Japanese"
weight = 10
[[languages.jp.menu.main]]
name = "ホーム"
url = "/jp"
weight = -99
[sitemap]
changefreq = "monthly"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
filename = "sitemap.xml"
priority = 0.5
[params]
  experience = 19
[taxonomies]
